dekarchive/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from users import views

urlpatterns = [
    path('', include('docs.urls')),
    path('admin/', admin.site.urls),
    path('register/', views.register_page, name='register'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_view, name='logout'),

    # Debug Tool Bar
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

docs/urls.py
from django.contrib import admin
from django.urls import path, include

from docs import views

app_name = 'docs'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('index/<str:status>', views.IndexView.as_view(), name='index'),
    path('index/<str:tag>', views.IndexView.as_view(), name='index-tag'),
    path('doc/<slug:slug>/', views.DocumentDetailView.as_view(), name='doc-detail'),
    path('image/<int:pk>', views.ImageDetailView.as_view(), name='image-detail'),

    path('create_doc/', views.CreateDocument.as_view(), name='create-doc'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Dek Document Archive</title>{% endblock %}

    <!-- Bootstrap5 css -->
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"-->
<!--          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">-->

    <!-- Bootstrap4 css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <!-- Bootswatch -->

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.0.2/dist/cerulean/bootstrap.min.css">-->
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.0.2/dist/litera/bootstrap.min.css">-->
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.0.2/dist/spacelab/bootstrap.min.css">-->
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.0.2/dist/journal/bootstrap.min.css">-->
<!--    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootswatch@5.0.2/dist/morph/bootstrap.min.css">-->

    <!-- Custom css -->
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
{% include 'navbar.html' %}


<div class="container">
{% block content %}

{% endblock %}
</div>
<!-- Bootsrap js -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
</body>
</html>

templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Dekker Archive</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <!-- Home -->
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'docs:home' %}">Home
                        <span class="visually-hidden">(current)</span>
                    </a>
                </li>
                <!-- Documents -->
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'docs:index' %}">Documents</a>
                </li>
                {% endif %}

<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">Pricing</a>-->
<!--                </li>-->
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link" href="#">About</a>-->
<!--                </li>-->
                <!-- Status -->
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                           aria-haspopup="true" aria-expanded="false">Document Status</a>
                        <div class="dropdown-menu">
                        <!-- 'c', 'Completed' -->
                        <!-- 'p', 'Pending' -->
                        <!-- 'n', 'See Notes' -->
                            <a class="dropdown-item" href="{% url 'docs:index' %}">All</a>
                            <a class="dropdown-item" href="{% url 'docs:index' 'c' %}">Completed</a>
                            <a class="dropdown-item" href="{% url 'docs:index' 'p' %}">Pending</a>
                            <a class="dropdown-item" href="{% url 'docs:index' 'n' %}">See Notes</a>
                        </div>
                    </li>
                {% endif %}
               <!-- Account dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button"
                       aria-haspopup="true" aria-expanded="false">Account</a>
                    <div class="dropdown-menu">
                    {% if request.user.is_authenticated %}
                        <a class="dropdown-item">Logged in as: <strong>{{ request.user.username }}</strong></a>
                        <a class="dropdown-item">Last log in: <strong>{{ request.user.last_login }}</strong></a>
                        <a class="dropdown-item" href="#">Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                        <a class="dropdown-item" href="{% url 'login' %}">Log in</a>
                        <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                    {% endif %}
                    </div>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<!-- End Navbar -->
</body>
</html>

templates/stuff.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Dekker Archive</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'docs:home' %}">Home</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'docs:index' %}">Documents</a>
                    </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                                Account
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% if request.user.is_authenticated %}
                            <li><a class="dropdown-item">Logged in as: <strong>{{ request.user.username }}</strong></a></li>
                            <li><a class="dropdown-item">Last log in: <strong>{{ request.user.last_login }}</strong></a></li>
                            <li><a class="dropdown-item" href="">Profile</a></li>
                            <div class="dropdown-divider"></div>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'login' %}">Log in</a></li>
                            <li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
                        {% endif %}
                    </ul>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'docs:create-doc' %}">Add Document</a>
                    </li>
                {% endif %}
            </ul>
            <form class="d-flex">
                <input class="form-control me-sm-2" type="text" placeholder="Search">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>