docs/urls.py
from django.contrib import admin
from django.urls import path, include

from docs import views

app_name = 'docs'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('index/<str:status>', views.IndexView.as_view(), name='index'),
    path('index/<str:tag>', views.IndexView.as_view(), name='index-tag'),
    path('doc/<slug:slug>/', views.DocumentDetailView.as_view(), name='doc-detail'),
    path('image/<int:pk>', views.ImageDetailView.as_view(), name='image-detail'),

    path('create_doc/', views.CreateDocument.as_view(), name='create-doc'),
]

docs/models.py
from datetime import datetime

from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill
from taggit.managers import TaggableManager


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Document(models.Model):
    JOB_STATUS = (
        ('c', 'Completed'),
        ('p', 'Pending'),
        ('n', 'See Notes'),
    )

    title = models.CharField(max_length=500, blank=False, null=False, unique=True)
    summary = models.CharField(max_length=500, blank=True, null=True)
    doc_date = models.DateField(blank=True, null=True, verbose_name='Document Date:')
    dutch_text = RichTextField(config_name='form_ckeditor', blank=True, null=True)
    english_text = RichTextField(config_name='form_ckeditor', blank=True, null=True)
    notes = RichTextField(config_name='form_ckeditor', blank=True, null=True)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=500, null=True, blank=True, unique=True)
    status = models.CharField(max_length=1, choices=JOB_STATUS, blank=False, default='p', help_text='Status')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Created:')
    updated = models.DateTimeField(auto_now=True, verbose_name='Updated:')
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    tags = TaggableManager(blank=True)

    def __str__(self):
        return self.title


def pre_save_document_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(str(instance.doc_date) + ' ' + str(instance.category) + ' ' + str(instance.title))


pre_save.connect(pre_save_document_receiver, sender=Document)


class DocImage(models.Model):
    caption = models.CharField(max_length=255, null=True, blank=True)
    image = models.ImageField(upload_to='images/documents')
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[ResizeToFill(210, 300)],
        format='JPEG'
    )
    doc = models.ForeignKey(Document, on_delete=models.CASCADE)

docs/templates/docs/forms.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, Button, Row, Column, Div, Field
from django import forms
from django.conf import settings

from docs.models import Document


class DateInput(forms.DateInput):
    input_type = 'date'
    input_format = settings.DATE_INPUT_FORMATS[0]


class CreateDocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = '__all__'
        widgets = {
            'doc_date': DateInput()
        }
        success_url = 'index/'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Hide labels of hidden fields
        self.fields['slug'].label = False
        self.fields['author'].label = False

        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Fieldset(
                'Create Document...',
                Row(
                    Div(Field('title', css_id="id_title"), css_class='col-md-3'),
                    Div(Field('summary', css_id="id_summary"), css_class='col-md-9'),
                ),
                Row(
                    Div(Field('doc_date', css_id='id_doc_date'), css_class='col-md-2'),
                    Div(Field('category', css_id='id_category'), css_class='col-md-2'),
                    Div(Field('status', css_id='id_status'), css_class='col-md-2'),
                ),
                Row(
                    Column(
                        Field('dutch_text'),
                        # css_class='col-md-2'
                    ),
                    Column(
                        Field('english_text'),
                        # css_class='col-md-5'
                    ),
                ),
                Row(
                    Column(
                        Field('notes'),
                        # css_class='col-md-5'
                    ),
                ),
            ),
            Field('slug', css_id='id_slug'),
            # Field('slug', css_id='id_slug', hidden=True),
            Field('author', css_id='id_author'),
            # Field('author', css_id='id_author', hidden=True),
            FormActions(
                Submit('save', 'Save'),
                Button('cancel', 'Cancel'),
            )
        )

docs/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView

from docs.models import Document, DocImage
from docs.templates.docs.forms import CreateDocumentForm


def home(request):
    return render(request, 'docs/home.html')


"""
TODO Filter on tag.
"""


class IndexView(ListView):
    model = Document
    template_name = 'docs/index.html'
    ordering = ['doc_date']
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data(*args, **kwargs)
        context['status'] = self.kwargs.get('status', None)
        return context

    def get_queryset(self, **kwargs):
        queryset = super(IndexView, self).get_queryset(**kwargs)
        # Filter by status.
        selection = self.kwargs.get('status', None)
        if selection:
            return queryset.filter(status=selection)

        return queryset


class DocumentDetailView(DetailView):
    model = Document
    template_name = 'docs/doc_detail.html'

    def get_context_data(self, **kwargs):
        context = super(DocumentDetailView, self).get_context_data(**kwargs)
        doc = get_object_or_404(Document, slug=self.kwargs['slug'])
        context['doc'] = doc
        return context


class ImageDetailView(DetailView):
    model = DocImage
    template_name = 'docs/image_detail.html'

    def get_context_data(self, **kwargs):
        context = super(ImageDetailView, self).get_context_data(**kwargs)
        if 'pk' in self.kwargs:
            context['docimage'] = get_object_or_404(DocImage, id=self.kwargs['pk'])

        return context


class CreateDocument(CreateView):
    model = Document
    form_class = CreateDocumentForm
    template_name = 'docs/create_doc.html'
    success_url = reverse_lazy('docs:index')

docs/templates/docs/create_doc.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<style>
    span.asteriskField {
    color: red;
    font-size: 15px;
</style>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {% crispy form %}
<!--    {{ form | crispy }}-->
<!--    <button type="submit" style="margin-top: 10px;" class="btn btn-primary">Save</button>-->
</form>

{% endblock %}}

docs/templates/docs/create_doc_bak.html
{% extends 'base.html' %}
{% block content %}

<form>
    {% csrf_token %}
    {{ form.media }}
    <fieldset>
    <legend>New Document</legend>
        <!-- Title -->
        <div class="form-group">
            <label for="id_title">Title</label>
            <input type="email" class="form-control" id="id_title" placeholder="Title of document">
        </div>
        <!-- Summary -->
        <div class="form-group">
            <label for="exampleInputSummary">Summary</label>
            <input type="email" class="form-control" id="exampleInputSummary" placeholder="Brief description of document.">
        </div>
        <!-- Date -->
        <div class="form-group">
            <label for="exampleInputDate">Date</label>
            <input type="email" class="form-control" id="exampleInputDate" placeholder="Date original document was created.">
        </div>
        <!-- Author AUTOMATIC = logged in user-->
        <div class="form-group">
        <label for="exampleSelect1">Author</label>
            <select class="form-select" id="exampleSelect1">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
            </select>
        </div>
        <!-- Single select -->
        <div class="form-group">
        <label for="exampleSelect2">Category</label>
            <select class="form-select" id="exampleSelect2">
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
            </select>
        </div>
        <!-- Dutch Text -->
        <div class="form-group">
            <label for="id_dutch_text">Dutch Text</label>
            <textarea class="form-control" id="id_dutch_text" rows="3"></textarea>
        </div>
        <!-- English Translation -->
        <div class="form-group">
            <label for="exampleTextarea1">English Translation</label>
            <textarea class="form-control" id="exampleTextarea1" rows="3"></textarea>
        </div>
        <!-- Notes -->
        <div class="form-group">
            <label for="exampleTextarea3">Notes</label>
            <textarea class="form-control" id="exampleTextarea3" rows="3"></textarea>
        </div>
        <!-- Select File -->
        <div class="form-group" style="margin-top: 10px;">
            <input type="file" name="images" multiple>
        </div>
        <!-- Save Button -->
        </fieldset>
        <button type="submit" style="margin-top: 10px;" class="btn btn-primary">Save</button>
    </fieldset>
</form>
{% endblock %}}

docs/templates/docs/doc_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!--<link rel="stylesheet" href="{% static 'css/card_list.css' %}">-->
<!-- Description -->
{% include 'docs/fragments/desc_fragment.html' %}

<ul class="nav nav-pills" id="myTab" role="tablist" style="margin-top: 20px;">
    <li class="nav-item" role="presentation">
        <button class="nav-link active" id="trans-tab" data-bs-toggle="tab" data-bs-target="#trans" type="button"
                role="tab" aria-controls="trans" aria-selected="true">Translation
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="notes-tab" data-bs-toggle="tab" data-bs-target="#notes" type="button"
                role="tab" aria-controls="notes" aria-selected="false">Notes
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="images-tab" data-bs-toggle="tab" data-bs-target="#images" type="button"
                role="tab" aria-controls="images" aria-selected="false">Images
        </button>
    </li>
    <li class="nav-item" role="presentation">
        <button class="nav-link" id="back-tab" data-bs-toggle="tab" data-bs-target="#back" type="button"
                role="tab" aria-controls="back" aria-selected="false"><a href="{% url 'docs:index' %}">Back</a>
        </button>
    </li>
</ul>

<div class="tab-content" id="myTabContent" style="background-color: #ffffff;">
    <!-- Translations -->
    <div class="tab-pane fade show active" id="trans" role="tabpanel" aria-labelledby="trans-tab">
        {% include 'docs/fragments/text_fragment.html' %}
    </div>
    <!-- Notes -->
    <div class="tab-pane fade" id="notes" role="tabpanel" aria-labelledby="notes-tab">
        {% include 'docs/fragments/notes_fragment.html' %}
    </div>
    <!-- Images -->
    <div class="tab-pane fade" id="images" role="tabpanel" aria-labelledby="images-tab">
        {% include 'docs/fragments/images_fragment.html' %}
    </div>
</div>

{% endblock %}

docs/templates/docs/fragments/desc_fragment.html
<!-- Description -->
<div class="row">
    <div class="col">
        <div class="card">
            <!-- Body -->
            <div class="card-body">
                <h5 class="card-title">{{ doc.title }}</h5>
            </div>
            <!-- Footer -->
            <div class="card-footer text-muted">
                {{ doc.category.name }} Dated: {{ doc.doc_date }} | Status: {{ doc.get_status_display }} | Created: {{ doc.created }} | Updated: {{ doc.updated }}
            </div>
        </div>
    </div>
</div>

docs/templates/docs/fragments/images_fragment.html
<div class="container" style="background-color: #f2f2f2; margin-top: 10px;">
    {% if doc.docimage_set.all %}
        <div class="row" style="width: 500px;">
            {% for img in doc.docimage_set.all %}
                <div class="col">
                    <figure class="figure">
                        <a href="{% url 'docs:image-detail' img.id %}">
                            <img src="{{ img.image_thumbnail.url }}" class="figure-img img-fluid rounded" alt="...">
                        </a>
                        <figcaption class="figure-caption">{{ img.caption }}</figcaption>
                    </figure>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>There are no images for this document.</p>
    {% endif %}
</div>

docs/templates/docs/fragments/notes_fragment.html
<!-- Notes -->
<div class="container" style="background-color: #f2f2f2; margin-top: 10px;">
    {% if doc.notes %}
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-text">
                        {{ doc.notes|safe }}
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <p>There are no notes for this document.</p>
    {% endif %}
</div>

docs/templates/docs/fragments/text_fragment.html
<!-- Text and Translation -->
<div class="row" style="background-color: #f2f2f2;">
    <!-- Dutch text -->
    <div class="col">
        <div class="card">
            <!-- Header -->
            <div class="card-header">
                Dutch Text
            </div>
            <!-- Body -->
            <div class="card-body">
                <p class="card-text">{{ doc.dutch_text|safe}}</p>
            </div>
        </div>
    </div>
    <!-- English Translation -->
    <div class="col">
        <div class="card">
            <!-- Header -->
            <div class="card-header">
                English Translation
            </div>
            <!-- Body -->
            <div class="card-body">
                <p class="card-text">{{ doc.english_text|safe}}</p>
            </div>
        </div>
    </div>
</div>

docs/templates/docs/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container py-4">
    <div class="p-5 mb-4 bg-light bg-light border rounded-3">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img">
            <title>Bootstrap</title>
            <path fill-rule="evenodd" clip-rule="evenodd"
                  d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"
                  fill="currentColor"></path>
        </svg>
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">Dekker Document Library</h1>
            <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one in
                previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to
                your liking.</p>
            <a href="{% url 'login' %}" class="btn btn-outline-primary">Login</a>
            <p>Don't have an account? Click <a href="{% url 'register' %}">here</a> to sign up.</p>
            {% for msg in messages %}
            <div class="alert alert-info" role="alert">
                {{ msg }}
            </div>
            {% endfor %}
        </div>
    </div>
    <footer class="pt-3 mt-4 text-muted border-top">
        Grey Nomad Engineering &copy; 2021
    </footer>
</div>
{% endblock %}

docs/templates/docs/image_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{ docimage.doc.title }}</h5>
    <p class="card-text">{{ docimage.caption }}</p>
      <p class="card-link"><small class="text-muted"><a href="javascript:history.go(-1)">Back</a></small></p>
  </div>
  <img src="{{ docimage.image.url }}" class="card-img-bottom" alt="...">
</div>
{% endblock %}

docs/templates/docs/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/card_list.css' %}">
<h2 style="margin-top: 10px; text-align: center;">
    {% if status == 'c' %}
        Completed translations.
    {% elif status == 'p' %}
        Pending translations.
    {% elif status == 'n' %}
        Translations with notes.
    {% else %}
        All translations.
    {% endif %}
</h2>
<div class="row">
    {% for doc in object_list %}
        <div class="col-sm-6">
            <div class="card">
                <!-- Header -->
                <div class="card-header">
                    {{ doc.category.name }} Dated: {{ doc.doc_date }}
                </div>
                <!-- Body -->
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'docs:doc-detail' doc.slug %}">{{ doc.title }}</a></h5>
<!--                    <h5 class="card-title"><a href="{% url 'docs:doc-detail' doc.pk %}">{{ doc.title }}</a></h5>-->
                    <p class="card-text">{{ doc.summary }}</p>
                </div>
                <!-- Tags -->
                {% if doc.tags.count %}
                    <div class="card-footer text-muted">
                        Tags:
                        {% for tag in doc.tags.all %}
                            <button type="submit" class="btn btn-outline-info" onclick="location.href='{% url 'docs:index-tag' tag %}'">
                                {{ tag }}
                            </button>
                        {% endfor %}
                    </div>
               {% endif %}
                <!-- Footer -->
                <div class="card-footer text-muted">
                    Status: {{ doc.get_status_display }} | Updated: {{ doc.updated }}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% if is_paginated %}
    <div class="container mt-2">
        <div class="row" style="margin-top: 20px;">
            <div class="col-lg-12">
                <ul class="pagination pagination">

                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1">&LeftArrowBar;</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&LeftArrow;</a>
                    </li>
                    {% endif %}

                    {% for page_num in page_obj.paginator.page_range %}
                        {% if page_obj.number == page_num %}
                        <li class="page-item active">
                            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                        </li>
                        {% elif page_num > page_obj.number|add:'-3' and page_num < page_obj.number|add:'3' %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                        </li>
                        {% endif %}
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">&RightArrow;</a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&RightArrowBar;</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
{% endif %}

{% endblock %}